services:
  postgres:
    # Ganti baris ini:
    image: postgres:18-alpine
    container_name: saas_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saas_image_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: saas_storage
    ports:
      - '9000:9000' # API Port
      - '9001:9001' # Console Port
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 miniouser miniopassword;
      /usr/bin/mc mb myminio/saas-bucket;
      /usr/bin/mc anonymous set download myminio/saas-bucket;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
